### ISSUE TITLE
How to create few shot data?

### ISSUE THREAD

**Issue by Wangpeiyi9979** [thunlp/Few-NERD#1]
Hi, thanks for your nice work.
After downloading data, I find there just a data file `supervised`.
I find few shot files are needed in the script :
`python3 train_demo.py  --train data/mydata/train-inter.txt
...`
Could you add some guide to create few shot data files like `train-inter.txt` in the readme? 
Thanks!

**Comment by Wangpeiyi9979** [comment]
Oh, I'm sorry I missed some details!

**Comment by cyl628** [comment]
the parameter should be --mode inter instead, I have updated the readme
