### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by ramybaly** [thunlp/Few-NERD#12]
Hello, thank you for creating this very interesting and important resource. I am trying to download the data, but getting a 502 Bad Gateway error from Nginx.

**Comment by ningding97** [comment]
> Hello, thank you for creating this very interesting and important resource. I am trying to download the data, but getting a 502 Bad Gateway error from Nginx.

Sorry for that, it may be because Tsinghua Cloud is not stable in the USA, have you solved the issue?

**Comment by demongolem-biz** [comment]
Yeah, I too have trouble with Tsinghua Cloud.  Are there any alternative repositories for the data?
