### ISSUE TITLE
Bug in few-shot sampling process

### ISSUE THREAD

**Issue by prohor33** [thunlp/Few-NERD#15]
Hi!
It seems like function  
https://github.com/thunlp/Few-NERD/blob/3935544c428a5ed0e78adaf29a9332cc91e8bda9/util/fewshotsampler.py#L62
has a bug, which affects sampling process.

You can see "for loop" and 4 "if" inside it. If flag `isvalid` is set to `True` or `False` in some iterations, it can be overwritten in next iterations of the loop. So, for example,  first class breaks the rule shots_count <= 2*K, but second class is new and flag `isvalid` will be returned as `True` from `__valid_sample__`, but sample breaks validation rules.

Thus, with this bug, we can sample samples, which are breaking sampling rules, e.g. with shots_count > 2*K.

What do you think? Does this bug affects results somehow? Maybe in the good way even.

**Comment by mtt1998** [comment]
Hi, I just find the released episodes for train/dev/test contain episodes that have support count > 2*K shot.

**Comment by cyl628** [comment]
Thanks for reminding! We have noticed the bug here and it does lead to some ">2*K shot" issues. We will fix the bug soon. The influence should be small, however, since it is not a frequent case.

**Comment by prohor33** [comment]
@cyl628 Hi! Why you have closed the bug? Have you fixed the bug?
