### ISSUE TITLE
OOM problem encountered with FewShotNERDatasetWithRandomSampling

### ISSUE THREAD

**Issue by RyanWangZf** [thunlp/Few-NERD#17]
When I try:

`python train_demo.py  --mode inter --lr 1e-4 --batch_size 8 --trainN 5 --N 5 --K 1 --Q 1 --train_iter 10000 --val_iter 500 --test_iter 5000 --val_step 1000 --max_length 64 --model structshot --tau 0.32`

the program gets stuck on line 399 of `framework.py` where it tries to get next `self.train_data_loader`. After a minute, it raises OOM problem.

I search for a whole night and find the __len__ function of FewShotNERDatasetWithRandomSampling returns 100000000000, which causes OOM error.

When I change it to `return len(self.samples)`, this problem disappears. Please fix it.

**Comment by cyl628** [comment]
Hi, you can change it to a smaller number if it causes OOM error on your machine. But we do not recommend using `len(self.samples)` because it will cause `StopIteration` error when you train on more than `len(self.samples)` iters.

**Comment by XinyanLi2016** [comment]
Hi, I also meet the same problem. When I change batch_size to 1, it also happens.

**Comment by cyl628** [comment]
you may try a smaller number for `len` function of FewShotNERDatasetWithRandomSampling
