### ISSUE TITLE
Question about the F1 score

### ISSUE THREAD

**Issue by yhcc** [thunlp/Few-NERD#2]
In the following ccode
https://github.com/thunlp/Few-NERD/blob/d95dba90a4c736a5310b7275d839ef7b786a46b7/util/framework.py#L537
average the F1 between batches. But this will make the evaluation results depend on the batch size chosen to conduct evaluation, right?

**Comment by cyl628** [comment]
the f1 score for each batch is calculated on entity-level, therefore, batch size won't have a big umpact on the evaluation result.

**Comment by yhcc** [comment]
I think the evaluation should not be dependent on the batch size (meaning should have no impact on the evaluation result). But take the following situation for example, if we have four samples, 
```
Within one batch(batch size is 4):
  golden: [
             [(PER, 0, 3), (LOC, 4, 5)], 
             [(PER, 0, 1)],
             [(ORG, 7, 9)], 
             [(GPE, 7, 9)], 
            ]
pred:  [
             [(PER, 0, 3), (PER, 4, 5)], 
             [(PER, 0, 1)],
             [(LOC, 7, 9)], 
             [(GPE, 7, 9)], 
            ]
The precision will be 3/5 and recall is also 3/5, therfore F1 is 3/5=15/20

However if the batch size is set to 1
the f1 will be [0.5, 1, 0, 1], making the average F1 2.5/4=12.5/20
```

**Comment by cyl628** [comment]
I think you are right on this. Thanks for pointing out. We will fix that soon.
