### ISSUE TITLE
the few-shot data and results.

### ISSUE THREAD

**Issue by Wangpeiyi9979** [thunlp/Few-NERD#22]
Hi, thanks for your nice work.

However, I just find the few-shot results of different versions of arXiv Papers are different.
There are three groups of results: {v1,v2} , {v3,v4,v5}, {v6}.

I notice some issues mentioned that :
(1) there are some imperfect implementations (such as hyperparameter selection and tokenization bug). 
(2) The sampled size was larger than 2K due to the data sampling bug.  

May I ask  if (1) is the cause of the result from {v1,v2} to {v3,v4,v5}?
And is (2) (different sampled few-shot datasets) the cause of the results from {v2, V4, V5} to {v6}?  
Or there are some other reasons.

This is really nice work, and thanks again for your open source and hard work  : ).
Look forward to your reply.

Thanks.

**Comment by cyl628** [comment]
Yes, and for the second change, we also re-run the model on the released few-shot data, i.e. add `--use_sampled_data` when running.

**Comment by Wangpeiyi9979** [comment]
thanks
