### ISSUE TITLE
为什么eval的时候老用cpu跑啊？

### ISSUE THREAD

**Issue by Qin-ai** [thunlp/Few-NERD#24]
真奇怪啊，eval的时候比train慢的好多，gpu一直为0，cpu却跑满了，感觉一直在用cpu跑，train的时候就没有这种情况

**Comment by cyl628** [comment]
Hi
I run `train_demo.py` on my server and found no issue with evaluation process. All computation is conducted on GPU. Maybe you can check your code again or give more detailed info of how you run the code.
