### ISSUE TITLE
您好，请问论文中提到的给few-nerd注释的接口代码是否公开了呢

### ISSUE THREAD

**Issue by KAYY123** [thunlp/Few-NERD#29]

**Comment by cyl628** [comment]
Hi, it is not clear which specific code you are asking. This repository contains codes for supervised training and few-shot training with 3 few-shot learning methods, i.e. protonet, nnshot and structshot. 

A kind reminder: plz raise issues in English so that everyone could understand :)

**Comment by KAYY123** [comment]
Hello.Sorry, I was not thoughtful enough.
Could you tell me is this code public?
![图片](https://user-images.githubusercontent.com/59907326/159151239-c4a86639-7226-4011-845d-5a70a71470e6.png)

**Comment by cyl628** [comment]
Oh this is not public. And I'm afraid we are not able to publicize it due to copyright issue.

**Comment by KAYY123** [comment]
Ok,Thank you.
