### ISSUE TITLE
Not using the Span F1?

### ISSUE THREAD

**Issue by yhcc** [thunlp/Few-NERD#3]
In the code  (and also the paper)
https://github.com/thunlp/Few-NERD/blob/d95dba90a4c736a5310b7275d839ef7b786a46b7/util/data_loader.py#L6
it seems like that if a tag sequence is ``O, B-Person, I-Person, B-Person, I-Person, O" (which has two entities) will be collapsed into sequence only contains one entity like ``O, Person, Person, Person, Person, O". Is my understanding correct?

**Comment by cyl628** [comment]
yes, we use `IO`-like labeling schema. The problem of two consecutive entities collapsing into one does exist, but that's a marginal situaton.
