### ISSUE TITLE
您好，我在bash run_supervised.sh的时候出现了如下报错，请问可能是什么原因呢？

### ISSUE THREAD

**Issue by KAYY123** [thunlp/Few-NERD#31]
![图片](https://user-images.githubusercontent.com/59907326/158047475-034bffa6-4c9c-4349-b938-3727cf455777.png)
![图片](https://user-images.githubusercontent.com/59907326/158047489-75d1c35d-6621-4d95-872b-588a7199eb65.png)
每次Iteration=1999的时候就会报错AttributeError: 'str' object has no attribute 'item'
请问可能是什么原因呢？谢谢！

**Comment by cyl628** [comment]
Hi, sorry for the oversight. It is an issue of inconsistent transformers version. The code has been modified to suit transformers 4.0.1.

**Comment by KAYY123** [comment]
Thank you!
