### ISSUE TITLE
Using custom dataset

### ISSUE THREAD

**Issue by homerjack** [thunlp/Few-NERD#37]
Hi, I attempted to use custom datasets by replacing respective data (under data/intra/train | test | dev.txt). However, I am encountering the error where I get either:

ZeroDivisionError when using proto model, or
![image](https://user-images.githubusercontent.com/62350810/174730459-1a73c24b-5dce-4a10-858e-4aa4a7dc68cb.png)

Cannot perform max on tensor with no elements
![image](https://user-images.githubusercontent.com/62350810/174730866-0f30dce2-ddc6-4ce5-8ee6-25ac47ffcec8.png)

Is there any other areas I should be amending in the data/code in order to use a custom dataset for it?

Thanks!

**Comment by pratikchhapolika** [comment]
Hi @homerjack are you able to train the model on your custom data?
