### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by loretoparisi** [thunlp/Few-NERD#4]
Hello,  thanks for this project. I was able to correctly train a `structshot` using the `train` script. Could you show how to correctly run the inference for an input sequence?
In my understanding, the loading would look like

```python
import os
import torch

from fewnerd.util.word_encoder import BERTWordEncoder
from fewnerd.model.proto import Proto
from fewnerd.model.nnshot import NNShot

# cache dir
cache_dir = os.getenv("cache_dir", "../../models")
model_path = 'structshot-inter-5-5-seed0.pth.tar'
model_name = 'structshot'
pretrain_ckpt = 'bert-base-uncased'
max_length = 100

# BERT word encoder
word_encoder = BERTWordEncoder(
        pretrain_ckpt,
        max_length)

if model_name == 'proto':
    # use dot instead of L2 distance for proto
    model = Proto(word_encoder, dot=True)
elif model_name == 'nnshot':
    model = NNShot(word_encoder, dot=False)
elif model_name == 'structshot':
    model = NNShot(word_encoder, dot=False)

model.load_state_dict(torch.load(os.path.join(cache_dir, model_path)))
```

but I get some errors on the state dicts (`RuntimeError: Error(s) in loading state_dict for NNShot:`) in this way...

Thank you in advance!

**Comment by cyl628** [comment]
to load the model properly, you can refer to 
https://github.com/thunlp/Few-NERD/blob/84c0b59fc0f8a8b265d025c6da2ebc139fdd2057/util/framework.py#L353

**Comment by pratikchhapolika** [comment]
@loretoparisi  are you able to do inferencing on the trained model?

**Comment by loretoparisi** [comment]
> @loretoparisi  are you able to do inferencing on the trained model?

thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...

**Comment by pratikchhapolika** [comment]
> > @loretoparisi  are you able to do inferencing on the trained model?
> 
> thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...

Ok. Thanks. Could you please attach your notebook code and data please.  @loretoparisi

**Comment by pratikchhapolika** [comment]
@cyl628 For a single input sequence, how should we write the inference script?

**Comment by loretoparisi** [comment]
> > > @loretoparisi  are you able to do inferencing on the trained model?
> 
> > 
> 
> > thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...
> 
> 
> 
> Ok. Thanks. Could you please attach your notebook code and data please.  @loretoparisi 

I have something [here](https://github.com/loretoparisi/hf-experiments/blob/master/src/fewnerd/README.md) I will add the inference code there!

**Comment by pratikchhapolika** [comment]
> > > > @loretoparisi  are you able to do inferencing on the trained model?
> > 
> > 
> > > 
> > 
> > 
> > > thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...
> > 
> > 
> > Ok. Thanks. Could you please attach your notebook code and data please.  @loretoparisi
> 
> I have something [here](https://github.com/loretoparisi/hf-experiments/blob/master/src/fewnerd/README.md) I will add the inference code there!

Please add the inference code and how the output looks like for singe input.

**Comment by pratikchhapolika** [comment]
> > > > @loretoparisi  are you able to do inferencing on the trained model?
> > 
> > 
> > > 
> > 
> > 
> > > thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...
> > 
> > 
> > Ok. Thanks. Could you please attach your notebook code and data please.  @loretoparisi
> 
> I have something [here](https://github.com/loretoparisi/hf-experiments/blob/master/src/fewnerd/README.md) I will add the inference code there!

@loretoparisi  Have you uploaded the inference script?

**Comment by loretoparisi** [comment]
> > > > > @loretoparisi  are you able to do inferencing on the trained model?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > thanks for the question, it was time ago, but I think so with some trick, I have to check the notebook for the code...
> 
> > > 
> 
> > > 
> 
> > > Ok. Thanks. Could you please attach your notebook code and data please.  @loretoparisi
> 
> > 
> 
> > I have something [here](https://github.com/loretoparisi/hf-experiments/blob/master/src/fewnerd/README.md) I will add the inference code there!
> 
> 
> 
> @loretoparisi  Have you uploaded the inference script?

not at this time, I will put it in the repo check updates, thanks.
