### ISSUE TITLE
What is the difference between episode-data model training and non-episode-data

### ISSUE THREAD

**Issue by pratikchhapolika** [thunlp/Few-NERD#43]
Inside `data/episode-data/inter/train_5_5.jsonl` I see lot of training, test and dev data. They are like `support` and `query` .

In the  `data/inter/train.txt` I see a different form of training data without `support` and `query` .

What is the purpose to keep these 2 formats of data?

**Does both are used to train few-shot learning?**

@cyl628

**Comment by cyl628** [comment]
Both format can be used for training.
`data/episode-data/inter/train_5_5.json` is the episodic data sampled from `data/inter/train.txt`. To run on it, simply add `--use_sampled_data` when running train_demo.py to train and test. 
Otherwise, the script will adopt a fewshotsampler to sample episodes online from `data/inter/train.txt`. See code
https://github.com/thunlp/Few-NERD/blob/2ad6a031b23f0ca1d8d830e0a129fa5ad82d2e44/util/fewshotsampler.py#L18

Using `data/episode-data/inter/train_5_5.json` makes your training results more stable and comparable.

**Comment by pratikchhapolika** [comment]
> 

@cyl628 Thank you for your quick response. 

So using this `class FewshotSampler: ` I can sample my custom-dataset also in `episode-way`. I have data-set that looks like this:

```
{   "word":
              [
                ["it", "was", "produced", "under", "the", "banner", "of", "pritish", "nandy", "communications", "and", "was", "written", "and", "directed", "by", "first", "time", "director", "saket", "chaudhary", "."],
                ["``", "the", "new", "york", "times", "``", "described", "the", "book", "as", "a", "``", "user", "'s", "manual", "for", "how", "to", "attract", "targeted", "traffic", "by", "a", "deeper", "understanding", "of", "google", "adsense", "code", "''", "."],
                ["the", "commodore", "1571", "is", "commodore", "'s", "high-end", "5\u00bc", "''", "floppy", "disk", "drive", "."],
                ["her", "interest", "in", "environmental", "and", "social", "issues", "led", "her", "to", "obtain", "a", "photography", "degree", "from", "edinburgh", "college", "of", "art", "and", "a", "m.a", "in", "photojournalism", "and", "documentary", "photography", "from", "the", "london", "college", "of", "communication", "in", "2006", "."],
                ["in", "1852", ",", "he", "sold", "a", "landscape", "painting", "``", "aus", "dem", "bondhusthal", "``", "(", "``", "from", "the", "bondhusdalen", "``", ")", ",", "to", "bridgewater", "gallery", "in", "london", "."]
              ],
      "label":
              [
                ["O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "person-director", "person-director", "O"],
                ["O", "art-other", "art-other", "art-other", "art-other", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"],
                ["O", "product-other", "product-other", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O"],
                ["O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "O", "other-educationaldegree", "other-educationaldegree", "O", "O", "O", "O", "O", "O", "O", "other-educationaldegree", "other-educationaldegree", "other-educationaldegree", "other-educationaldegree", "other-educationaldegree", "other-educationaldegree", "O", "O", "O", "O", "O", "O", "O", "O", "O"],
                ["O", "O", "O", "O", "O", "O", "O", "O", "O", "art-painting", "art-painting", "art-painting", "O", "O", "O", "art-painting", "art-painting", "art-painting", "O", "O", "O", "O", "O", "O", "O", "O", "O"]
              ]

      "types": ["art-other", "product-other", "other-educationaldegree"]
 }
```

**Comment by pratikchhapolika** [comment]
> Both format can be used for training. `data/episode-data/inter/train_5_5.json` is the episodic data sampled from `data/inter/train.txt`. To run on it, simply add `--use_sampled_data` when running train_demo.py to train and test. Otherwise, the script will adopt a fewshotsampler to sample episodes online from `data/inter/train.txt`. See code
> 
> https://github.com/thunlp/Few-NERD/blob/2ad6a031b23f0ca1d8d830e0a129fa5ad82d2e44/util/fewshotsampler.py#L18
> 
> Using `data/episode-data/inter/train_5_5.json` makes your training results more stable and comparable.

@cyl628 

Does this `class FewshotSampler:` converts whole data `data/inter/train.txt.` into episode fashioned way or just one sample at a time?

**Comment by cyl628** [comment]
What do you mean by `just one sample at a time`? You can read the code for `FewShotSampler`, it basically randomly samples a given number of episodes from `train.txt`. A single sample in `train.txt` may appear in more than one episodes.

**Comment by pratikchhapolika** [comment]
> What do you mean by `just one sample at a time`? You can read the code for `FewShotSampler`, it basically randomly samples a given number of episodes from `train.txt`. A single sample in `train.txt` may appear in more than one episodes.

@cyl628 , I mean does it converts the whole data `data/inter/train.txt.` and convert it into episode. ?   Or if choose say 50,000 episodes and then it will choose from `data/inter/train.txt.` and convert in `50,000 episodes` having support and query.
