### ISSUE TITLE
I've got ERROR 404:Not Found when I try to download through bash file 

### ISSUE THREAD

**Issue by minstar** [thunlp/Few-NERD#46]
Hi, I have tried to download the data through suggested commands such as below, 
```bash data/download.sh supervised```

However, I've got the not found error on this.
![image](https://user-images.githubusercontent.com/24719775/202387003-d113e613-3ab4-46c3-8270-c56b87cf3f4f.png)

Could you help me how to get the data?

**Comment by minstar** [comment]
Oh I think I have forked the out-of-date version.
I figured it out by updating the version.

**Comment by zxzx117** [comment]
hi,What have you updated?
