### ISSUE TITLE
About the performance

### ISSUE THREAD

**Issue by Yifan-Song793** [thunlp/Few-NERD#5]
Good Work!
We test the model (5-way 5~10-shot ProtoBERT inter) using the following script:
```shell
python train_demo.py  --mode inter \
--lr 1e-3 --batch_size 5 --trainN 5 --N 5 --K 5 --Q 5 \
--train_iter 10000 --val_iter 500 --test_iter 5000 --val_step 1000 \
--max_length 60 --model proto
```
and this is our result:
p: 0.4772, r: 0.5795, f1: 0.5228
It significantly outperforms the result reported in your paper (p: 0.3609, r: 0.4996, f1: 0.4186)

Could you please expain the result?
Thanks!

**Comment by ningding97** [comment]
> Good Work!
> We test the model (5-way 5~10-shot ProtoBERT inter) using the following script:
> 
> ```shell
> python train_demo.py  --mode inter \
> --lr 1e-3 --batch_size 5 --trainN 5 --N 5 --K 5 --Q 5 \
> --train_iter 10000 --val_iter 500 --test_iter 5000 --val_step 1000 \
> --max_length 60 --model proto
> ```
> 
> and this is our result:
> p: 0.4772, r: 0.5795, f1: 0.5228
> It significantly outperforms the result reported in your paper (p: 0.3609, r: 0.4996, f1: 0.4186)
> 
> Could you please expain the result?
> Thanks!

Hi, the results in the accepted version of the paper are influenced by a number of random factors and they are not the latest results. We re-run a series of experiments and we will soon update the paper in arxiv. The latest performance in this setting is:

46.88±0.27;  59.54±1.10; 52.42±0.6.

Thanks

**Comment by Yifan-Song793** [comment]
Thank you!
